server.port=8081
server.servlet.context-path=/api

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/ubt_db?useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Prajwal@8275
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hikari
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# File upload
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# JWT
app.jwt.secret=UBTTechnologyIncubationSecretKey2025NagpurMaharashtraSecure
app.jwt.expiration=86400000

# CORS
app.cors.allowed-origins=http://localhost:5173,http://localhost:5174

app.admin.password=ubtech@admin2025

cloudinary.cloud-name=dhzxgxnvb
cloudinary.api-key=498599969519675
cloudinary.api-secret=bZ5E7sNysqsXxdYKWmV3jc_XbJE